apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-wemanity
  name: nginx-wemanity
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
       claimName: pv-claim
  containers:
  - image: nginx
    name: nginx-wemanity
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: pv-storage
  - image: fabx/git-sync:latest
    name: git-sync
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: pv-storage
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
